### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Netflix/titus-control-plane#919]
https://github.com/Netflix/titus-control-plane/blob/cc89c5334fbfedede530e6209e45eede2cb1bc0e/titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/AmazonClientProvider.java#L33-L35

https://github.com/Netflix/titus-control-plane/blob/cc89c5334fbfedede530e6209e45eede2cb1bc0e/titus-ext/aws/src/main/java/com/netflix/titus/ext/aws/AmazonClientProvider.java#L52-L55

double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.

**Comment by fabiokung** [comment]
Thanks, we do not target platform independency today. Closing
