### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Netflix/titus-control-plane#920]
https://github.com/Netflix/titus-control-plane/blob/cc89c5334fbfedede530e6209e45eede2cb1bc0e/titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/tool/command/CreateKeyspaceCommand.java#L106

The program can potentially fail to release a system resource.

**Comment by FelipeF1198** [comment]
> https://github.com/Netflix/titus-control-plane/blob/cc89c5334fbfedede530e6209e45eede2cb1bc0e/titus-ext/cassandra/src/main/java/com/netflix/titus/ext/cassandra/tool/command/CreateKeyspaceCommand.java#L106
> 
> The program can potentially fail to release a system resource.
